# Generated by Django 3.2 on 2022-09-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена товара')),
                ('image', models.URLField(verbose_name='Изображение товара')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.category')),
            ],
        ),
    ]
